<?php
/** @var \Moehrenzahn\Toolkit\View\Taxonomy\Meta $view */
?>
<tr class="form-field">
    <th><label for="<?php echo $view->getSlug(); ?>"><?php echo $view->getTitle(); ?></label></th>
    <td>
        <p>
        <label for="<?php echo $view->getSlug(); ?>">
            <input type="checkbox"
                   value="<?php echo $view->getSlug(); ?>"
                   name="<?php echo $view->getSlug(); ?>"
                   id="<?php echo $view->getSlug(); ?>"
                <?php echo $view->getValue() ? 'checked' : ''; ?>
            >
            <?php echo $view->getDescription(); ?>
        </label>
        </p>
    </td>
</tr>
