<?php
/** @var \Moehrenzahn\Toolkit\View\Taxonomy\Meta $view */
$imageUrl = wp_get_attachment_url($view->getValue() ?? '');
wp_enqueue_media();
?>
<input type='hidden'
       name='<?php echo $view->getSlug(); ?>'
       id='<?php echo $view->getSlug(); ?>'
       value='<?php echo $view->getValue(); ?>'>

<tr class="form-field">
    <th><?php echo $view->getTitle(); ?></th>
    <td>
        <label  for="<?php echo $view->getSlug(); ?>">
            <input id="<?php echo $view->getSlug(); ?>-button"
                   type="image"
                   height="150"
                   width="200"
                   style="background: lightgray;object-fit: cover"
                   alt="Click here to select media"
                   src='<?php echo $imageUrl; ?>'/>
            <input id="<?php echo $view->getSlug(); ?>-remove" type="button" class="button" value="Remove"/>
            <?php echo $view->getDescription(); ?>
        </label>
    </td>
</tr>

<script>
    jQuery(document).ready(function ($) {
        initMediaSelector(
            '<?php echo $view->getValue(); ?>',
            '<?php echo $view->getSlug(); ?>-button',
            '<?php echo $view->getSlug(); ?>',
            '<?php echo $view->getSlug(); ?>-remove'
        );
    });
</script>
