<?php
/** @var \Moehrenzahn\Toolkit\Block\Taxonomy\Meta $block */
?>
<tr class="form-field">
    <th><?php echo $block->getTitle(); ?></th>
    <td>
        <label  for="<?php echo $block->getSlug(); ?>">
            <select name="<?php echo $block->getSlug(); ?>"
                    id="<?php echo $block->getSlug(); ?>">
                <?php foreach ($block->getOptions() as $optionSlug => $optionName) : ?>
                    <option value="<?php echo $optionSlug; ?>"
                        <?php echo ($optionSlug === $block->getValue()) ? 'selected' : ''; ?>>
                        <?php echo $optionName; ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <?php echo $block->getDescription(); ?>
        </label>
    </td>
</tr>
