<?php
/** @var \Moehrenzahn\Toolkit\View\Taxonomy\Meta $view */
?>
<tr class="form-field">
    <th><?php echo $view->getTitle(); ?></th>
    <td>
        <label  for="<?php echo $view->getSlug(); ?>">
            <select name="<?php echo $view->getSlug(); ?>"
                    id="<?php echo $view->getSlug(); ?>">
                <?php foreach ($view->getOptions() as $optionSlug => $optionName) : ?>
                    <option value="<?php echo $optionSlug; ?>"
                        <?php echo ($optionSlug === $view->getValue()) ? 'selected' : ''; ?>>
                        <?php echo $optionName; ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <?php echo $view->getDescription(); ?>
        </label>
    </td>
</tr>
