<?php
/** @var \Moehrenzahn\Toolkit\View\Taxonomy\Meta $view */
?>

<tr class="form-field">
    <th><?php echo $view->getTitle(); ?></th>
    <td>
        <label  for="<?php echo $view->getSlug(); ?>">
            <textarea rows="10"
                      name="<?php echo $view->getSlug(); ?>"
                      id="<?php echo $view->getSlug(); ?>"
            ><?php echo esc_textarea($view->getValue()); ?></textarea>
            <?php echo $view->getDescription(); ?>
        </label>
    </td>
</tr>
