<?php
/** @var \Moehrenzahn\Toolkit\View\Taxonomy\Meta $view */
?>
<tr class="form-field">
    <th><?php echo $view->getTitle(); ?></th>
    <td>
        <label  for="<?php echo $view->getSlug(); ?>">
            <input name="<?php echo $view->getSlug(); ?>"
                   type="text"
                   id="<?php echo $view->getSlug(); ?>"
                   value="<?php echo $view->getValue(); ?>">
            <?php echo $view->getDescription(); ?>
        </label>
    </td>
</tr>
