<?php
/** @var Moehrenzahn\Toolkit\View $view */
/** @var array $data */
$id = uniqid('lazy-');
?>
<section id="<?php echo $id ?>">
    <?php $view->renderPartial($data['placeholder']); ?>
</section>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        loadTemplate(
            '<?php echo $data['template']; ?>',
            document.querySelector('#<?php echo $id; ?>'),
            '<?php echo addslashes($data['viewClass']); ?>',
            <?php echo $data['postId']; ?>
        );
    }, false);
</script>