<?php
/** @var \Moehrenzahn\Toolkit\Api\BlockInterface $block */
/** @var array $data */
?>
<img class='image-lazy loading js-only <?php echo $data['classList']; ?>'
     src='<?php echo $data['placeholderUrl']; ?>'
     data-full='<?php echo $data['url']; ?>'
     data-placeholder='<?php echo $data['placeholderUrl']; ?>'
     <?php echo $data['lazyLoadScript']; ?>
/>
<noscript>
    <?php echo $block->renderPartial(TOOLKIT_TEMPLATE_FOLDER . 'LazyImageFallback', null, $data); ?>
</noscript>