<?php /** @var \Moehrenzahn\Toolkit\View\Settings\Setting $view */ ?>
<?php $setting = $view->getSetting(); ?>
<input type='hidden' value='0' name='<?php echo $setting->getId(); ?>'>

<label class="description">
    <input name="<?php echo $setting->getId(); ?>"
           type="checkbox"
           data-depends="<?php echo implode(';', $view->getDepends()); ?>"
           id="<?php echo $setting->getId(); ?>"
           <?php echo $setting->getValue() ? 'checked' : ''; ?>>
    <?php echo $setting->getDescription(); ?>
</label>