<?php
/** @var \Moehrenzahn\Toolkit\View\Settings\Setting $view */
/** @var \Moehrenzahn\Toolkit\Model\AdminPage\Settings\Setting $setting */
$setting = $view->getSetting();
?>
<a class="button btn"
   data-depends="<?php echo implode(';', $view->getDepends()); ?>"
   href="<?php echo admin_url('admin-post.php?action=' . $setting->getId()); ?>">
    <?php echo $setting->getTitle(); ?>
</a>
<p class="description"><?php echo $setting->getDescription(); ?></p>