<?php /** @var \Moehrenzahn\Toolkit\Block\Settings\Setting $block */ ?>
<?php
$setting = $block->getSetting();
$imageUrl = wp_get_attachment_url($setting->getValue()) ?? '';
?>
<input type='hidden'
       name='<?php echo $setting->getId(); ?>'
       id='<?php echo $setting->getId(); ?>'
       value='<?php echo $setting->getValue(); ?>'>

<label>
    <input id="<?php echo $setting->getId(); ?>-button"
           type="image"
           width="100"
           height="100"
           alt="<?php echo $setting->getTitle(); ?>"
           src='<?php echo $imageUrl; ?>'/>
</label>
<input id="<?php echo $setting->getId(); ?>-remove" type="button" class="button" value="Leeren"/>
<p class="description">
    <?php echo $setting->getDescription(); ?>
</p>

<script>
    jQuery(document).ready(function ($) {
        initMediaSelector(
            '<?php echo $setting->getValue(); ?>',
            '<?php echo $setting->getId(); ?>-button',
            '<?php echo $setting->getId(); ?>',
            '<?php echo $setting->getId(); ?>-remove'
        );
    });
</script>