<?php
/** @var \Moehrenzahn\Toolkit\View\Settings\Setting $view */
$setting = $view->getSetting();
$imageUrl = wp_get_attachment_url($setting->getValue()) ?? '';
wp_enqueue_media();
?>
<input type='hidden'
       name='<?php echo $setting->getId(); ?>'
       id='<?php echo $setting->getId(); ?>'
       value='<?php echo $setting->getValue(); ?>'>

<label>
    <input id="<?php echo $setting->getId(); ?>-button"
           type="image"
           height="150"
           width="200"
           style="background: lightgray;object-fit: cover"
           alt="Click here to select media"
           src='<?php echo $imageUrl; ?>'/>
</label>
<input id="<?php echo $setting->getId(); ?>-remove" type="button" class="button" value="Remove"/>
<p class="description">
    <?php echo $setting->getDescription(); ?>
</p>

<script>
    jQuery(document).ready(function ($) {
        initMediaSelector(
            '<?php echo $setting->getValue(); ?>',
            '<?php echo $setting->getId(); ?>-button',
            '<?php echo $setting->getId(); ?>',
            '<?php echo $setting->getId(); ?>-remove'
        );
    });
</script>