<?php /** @var \Moehrenzahn\Toolkit\View\Settings\Setting $view */

use Moehrenzahn\Toolkit\Api\Model\Settings\SettingInterface; ?>
<?php
/** @var SettingInterface $setting */
$setting = $view->getSetting();
?>
<select name="<?php echo $setting->getId(); ?>"
        data-depends="<?php echo implode(';', $view->getDepends()); ?>"
        id="<?php echo $setting->getId(); ?>">
    <?php foreach ($setting->getOptions() as $optionSlug => $optionName) : ?>
        <option value="<?php echo $optionSlug; ?>"
            <?php echo ((string)$optionSlug === (string)$setting->getValue()) ? 'selected' : ''; ?>>
            <?php echo $optionName; ?>
        </option>
    <?php endforeach; ?>
</select>
<p class="description"><?php echo $setting->getDescription(); ?></p>
