<?php /** @var \Toolkit\Block\Settings\Setting $block */ ?>
<?php $setting = $block->getSetting(); ?>
<input type='hidden' value='0' name='<?php echo $setting->getId(); ?>'>

<div>
    <input name="<?php echo $setting->getId(); ?>"
           type="checkbox"
           id="<?php echo $setting->getId(); ?>"
        <?php echo $setting->getValue() ? 'checked' : ''; ?>>
    <label for="<?php echo $setting->getId(); ?>">
        <?php echo $setting->getTitle(); ?>
    </label>
    <p class="description">
    <?php echo $setting->getDescription(); ?>
</p>
</div>