<?php
/** @var \Moehrenzahn\Toolkit\Api\ViewInterface $view */
/** @var \Moehrenzahn\Toolkit\Model\Post\PostPreference $setting */
$setting = $view->getData('preference');
$imageUrl = wp_get_attachment_url($setting->getValue($view->getPost()->ID)) ?? '';
wp_enqueue_media();
?>
<input type='hidden'
       name='<?php echo $setting->getId(); ?>'
       id='<?php echo $setting->getId(); ?>'
       value='<?php echo $setting->getValue($view->getPost()->ID); ?>'>

<label for="<?php echo $setting->getId(); ?>">
    <?php echo $setting->getTitle(); ?>
</label>
<div>
    <input id="<?php echo $setting->getId(); ?>-button"
           type="image"
           height="150"
           style="width: 100%;background:lightgray;object-fit: cover"
           alt="Click here to select media"
           src='<?php echo $imageUrl; ?>'/>
</div>
<p class="description">
    <?php echo $setting->getDescription(); ?>
    <a href="#" id="<?php echo $setting->getId(); ?>-remove">Remove</a>
</p>

<script>
    jQuery(document).ready(function ($) {
        initMediaSelector(
            '<?php echo $setting->getValue($view->getPost()->ID); ?>',
            '<?php echo $setting->getId(); ?>-button',
            '<?php echo $setting->getId(); ?>',
            '<?php echo $setting->getId(); ?>-remove'
        );
    });
</script>