<?php
$setting = $block->getData('preference');
$imageUrl = wp_get_attachment_url($setting->getValue($block->getPost()->ID)) ?? '';
wp_enqueue_media();
?>
<input type='hidden'
       name='<?php echo $setting->getId(); ?>'
       id='<?php echo $setting->getId(); ?>'
       value='<?php echo $setting->getValue($block->getPost()->ID); ?>'>

<label for="<?php echo $setting->getId(); ?>">
    <?php echo $setting->getTitle(); ?>
</label>
<div>
    <input id="<?php echo $setting->getId(); ?>-button"
           type="image"
           width="100"
           style="min-height:50px;background: lightgray"
           alt="<?php echo $setting->getTitle(); ?>"
           src='<?php echo $imageUrl; ?>'/>
    <input id="<?php echo $setting->getId(); ?>-remove" type="button" class="button" value="Entfernen"/>
</div>
<p class="description">
    <?php echo $setting->getDescription(); ?>
</p>

<script>
    jQuery(document).ready(function ($) {
        initMediaSelector(
            '<?php echo $setting->getValue($block->getPost()->ID); ?>',
            '<?php echo $setting->getId(); ?>-button',
            '<?php echo $setting->getId(); ?>',
            '<?php echo $setting->getId(); ?>-remove'
        );
    });
</script>