<?php
$setting = $block->getData('preference');
?>
<div>
    <label for="<?php echo $setting->getId(); ?>">
        <?php echo $setting->getTitle(); ?>
    </label>
    <select name="<?php echo $setting->getId(); ?>"
            id="<?php echo $setting->getId(); ?>">
        <?php foreach ($setting->getOptions() as $optionSlug => $optionName) : ?>
            <option value="<?php echo $optionSlug; ?>"
                <?php echo ($optionSlug === $setting->getValue($block->getPost()->ID)) ? 'selected' : ''; ?>>
                <?php echo $optionName; ?>
            </option>
        <?php endforeach; ?>
    </select>
    <p class="description"><?php echo $setting->getDescription(); ?></p>
</div>
