<?php $setting = $view->getData('preference'); ?>
<div>
    <label for="<?php echo $setting->getId(); ?>">
        <?php echo $setting->getTitle(); ?>
    </label>
    <div>
        <input name="<?php echo $setting->getId(); ?>"
               type="text"
               style="width: 100%"
               id="<?php echo $setting->getId(); ?>"
               value="<?php echo $setting->getValue($view->getPost()->ID); ?>">
    </div>
    <p class="description"><?php echo $setting->getDescription(); ?></p>
</div>