<?php /** @var \Toolkit\Block\Settings\Setting $block */ ?>
<?php $setting = $block->getSetting(); ?>
<label for="<?php echo $setting->getId(); ?>">
    <?php echo $setting->getTitle(); ?>
</label>
<div>
    <textarea rows="10"
              name="<?php echo $setting->getId(); ?>"
              id="<?php echo $setting->getId(); ?>"
    ><?php echo esc_textarea($setting->getValue()); ?></textarea>
</div>
<p class="description"><?php echo $setting->getDescription(); ?></p>