<?php /** @var \Toolkit\Block\Settings\Setting $block */ ?>
<?php $setting = $block->getSetting(); ?>
<div>
    <label for="<?php echo $setting->getId(); ?>">
        <?php echo $setting->getTitle(); ?>
    </label>
    <div>
        <input name="<?php echo $setting->getId(); ?>"
               type="text"
               id="<?php echo $setting->getId(); ?>"
               value="<?php echo $setting->getValue(); ?>">
    </div>
    <p class="description"><?php echo $setting->getDescription(); ?></p>
</div>