<?php $setting = $block->getData('preference'); ?>
<label for="<?php echo $setting->getId(); ?>">
    <?php echo $setting->getTitle(); ?>
</label>
<div>
    <textarea rows="10"
              name="<?php echo $setting->getId(); ?>"
              id="<?php echo $setting->getId(); ?>"
    ><?php echo esc_textarea($setting->getValue($block->getPost()->ID)); ?></textarea>
</div>
<p class="description"><?php echo $setting->getDescription(); ?></p>